### ISSUE TITLE
BasicDropdown doesn't appear to be attaching any event listeners

### ISSUE THREAD

**Issue by Cerzi** [cibernox/ember-basic-dropdown#481]
Using version 3.11b3 of Ember and version 2.0.0 of basic dropdown, none of my dropdowns are responding to click events.  When inpsecting the event listeners for the div, there aren't any associated with basic-dropdown, unlike when inspecting the example dropdowns in the documentation.

Does anyone have any idea why this might be the case, even for the most simple example?
```
<BasicDropdown as |dd|>
  <dd.Trigger>Click me</dd.Trigger>
  <dd.Content>Hello world</dd.Content>
</BasicDropdown>
```

**Comment by cibernox** [comment]
No idea really. The tests are passing and the documentation is using ember 3.11.

Can you provide a reproduction? Does it work on a clean app?

**Comment by Cerzi** [comment]
In a clean app there's something a bit unexpected happening - with just ember-basic-dropdown installed and a simple template with the above example dropdown, this exception is thrown
```
Uncaught Error: Compile Error: or is not a helper
    at opcode-compiler.js:294
```

If I also install ember-power-select, this exception goes away but I have the same problem as my other app - no event listener is added and mouse clicks do not cause any triger to occur on the dropdown...

**Comment by Cerzi** [comment]
These are the dev dependencies of the clean app (+ basic-dropdown and power-select)
```
  "devDependencies": {
    "@ember/jquery": "^0.6.0",
    "@ember/optional-features": "^0.7.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^5.0.0",
    "ember-basic-dropdown": "^2.0.1",
    "ember-cli": "~3.11.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.7.3",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-power-select": "^3.0.0",
    "ember-qunit": "^4.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.10.0",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "^6.2.0",
    "eslint-plugin-node": "^9.0.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.4",
    "sass": "^1.22.4"
  },
```

**Comment by cibernox** [comment]
@Cerzi that was actually very helpful, I've detected a bug thanks to that. I released 2.0.2 that should at least fix your 
```
Uncaught Error: Compile Error: or is not a helper
    at opcode-compiler.js:294
```

**Comment by Cerzi** [comment]
Excellent!  Ill take another look tomorrow and see if the event issue persists in the clean project.  Seems like it might be something wrong with my setup specifically though

**Comment by JenLyndle** [comment]
I am facing this same issue. Am on Ember 3.11 and I have a clean project. I installed ember-basic-dropdown and looks like no event handlers are attached. I tried updating to the 2.0.2 and the issue persists.
These are my devDependencies:

  "devDependencies": {
    "@ember/jquery": "^0.6.0",
    "@ember/optional-features": "^0.7.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^5.0.0",
    "ember-basic-dropdown": "^2.0.2",
    "ember-cli": "~3.10.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.7.3",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.10.0",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "^6.2.0",
    "eslint-plugin-node": "^9.0.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.4"
  }
I see no error in the console. Is there anything I am missing?

**Comment by cibernox** [comment]
@JenLyndle you are using ember 3.10, and EBD 2.0 requires 3.11 https://github.com/cibernox/ember-basic-dropdown#compatibility

**Comment by JenLyndle** [comment]
@cibernox sorry about that. I upgraded to ember 3.11 and tried again but unfortunately it still did not work. I have attached my code:
[test-dropdown.zip](https://github.com/cibernox/ember-basic-dropdown/files/3403317/test-dropdown.zip)
These are my devdependencies now:
{
  "name": "test-dropdown",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for test-dropdown goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember/jquery": "^0.6.0",
    "@ember/optional-features": "^0.7.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-ajax": "^5.0.0",
    "ember-basic-dropdown": "^2.0.2",
    "ember-cli": "3.11.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.7.3",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "^3.0.1",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-data": "~3.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.10.0",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "^6.2.0",
    "eslint-plugin-node": "^9.0.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.4"
  },
  "engines": {
    "node": "8.* || >= 10.*"
  }
}

Please let me know if there is anything else I should be doing.

**Comment by cibernox** [comment]
@JenLyndle for what I can see, you're still in Ember 3.10

```
"ember-source": "~3.10.0",
```

**Comment by JenLyndle** [comment]
Thanks @cibernox! sorry for wasting your time on such a silly mistake in my part.
